name: Verify Website Container Builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-launch-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t website-test .