name: Test Docker Container Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-docker-build:
    uses: ChaosCantrip/DestinyTCG/.github/workflows/build-test.yml@main