name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY_URL: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short commit SHA
        id: commit_sha
        run: echo "SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the image
        run: |
          docker build -t ${{ env.REGISTRY_URL }}/${{ env.REPO_NAME }}/website:latest ./apps/website
          docker tag ${{ env.REGISTRY_URL }}/${{ env.REPO_NAME }}/website:latest ${{ env.REGISTRY_URL }}/${{ env.REPO_NAME }}/website:$SHA_SHORT
          docker push ${{ env.REGISTRY_URL }}/${{ env.REPO_NAME }}/website:latest
          docker push ${{ env.REGISTRY_URL }}/${{ env.REPO_NAME }}/website:$SHA_SHORT