name: Rebase dev onto main

on:
  push:
    branches:
      - main

jobs:
  rebase-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "ChaosCantrip [Automated]"
          git config user.email "dev@chaoscantrip.com"

      - name: Rebase dev onto main
        run: |
          git fetch origin
          git checkout dev || git checkout -b dev
          git rebase origin/main
          git push origin dev --force-with-lease