name: DestinyTCG Submodule Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  submodule-workflow:
    uses: ChaosCantrip/DestinyTCG/.github/workflows/submodule-workflow.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      commit-sha: ${{ github.event.pull_request.head.sha }}
      submodule-reference: "website"
    secrets:
      monorepo-read-pat: ${{ secrets.MONOREPO_READ_PAT }}
      monorepo-write-pat: ${{ secrets.MONOREPO_WRITE_PAT }}